In [2]:
import pandas as pd

In [15]:
a = pd.read_csv('details.csv')
a

                    Name                              Mail   Location  Maths
0          Smriti Ranjan          smritiranjan65@gmail.com      Patna     93
1          Tannu kumari            tkumari930451@gmail.com      Patna     78
2                  Seema         dksainiaggarwal@gmail.com   Dehradun     78
3          Mukesh Nirmal         nirmalmukesh200@gmail.com   Dehradun     72
4                  rohit                               NaN        NaN     87
5               Ramakant     ramakantprajapati11@gmail.com   Dehradun     75
6    Vinod Kumar Sharma        vinodsharma740860@gmail.com     Kanpur     74
7     Gulshan Kumar Ray            raygulshan960@gmail.com   Dehradun     83
8    Ashutosh Kumar raj           ashutoshraj822@gmail.com      Patna     89
9             Amit kumar          amitpatel8340s@gmail.com      Patna     73
10          Astha sachan           asthasachan96@gmail.com     Kanpur     77
11          Shail Kumari           shailverma945@gmail.com     Kanpur     80
12  Vaishnavi Kesherwani  vaishnavikesherwani786@gmail.com  Allahabad     88
13             Rahul Rai           rahul.rai8997@gmail.com   Dehradun     76
14                Trapti          traptishakya21@gmail.com  Allahabad     74
15       Annapurna Rawat           nainarawat003@gmail.com  Allahabad     79

In [16]:
b = pd.read_csv('marks.csv')
b

                    Name  English  Hindi  Maths  Science  Social Science
0          Smriti Ranjan       85     83     93       91              94
1          Tannu kumari        90     75     78       73              75
2                  Seema       93     75     78       89              94
3          Mukesh Nirmal       92     71     72       96              75
4                  rohit       75     78     87       90              87
5               Ramakant       84     76     75       76              96
6    Vinod Kumar Sharma        75     94     74       81              71
7     Gulshan Kumar Ray        73     74     83       76              94
8    Ashutosh Kumar raj        89     70     89       97              81
9             Amit kumar       80     71     73       87              96
10          Astha sachan       77     71     77       93              72
11          Shail Kumari       95     97     80       92              92
12  Vaishnavi Kesherwani       82     90     88       91              71
13             Rahul Rai       75     77     76       80              78
14                Trapti       91     95     74       94              98
15       Annapurna Rawat       70     75     79       96              80

In [8]:
pd.merge(a,b)

,Name,Mail,Location,Maths,English,Hindi,Science,Social Science
0,Smriti Ranjan,smritiranjan65@gmail.com,Patna,93,85,83,91,94
1,Tannu kumari,tkumari930451@gmail.com,Patna,78,90,75,73,75
2,Seema,dksainiaggarwal@gmail.com,Dehradun,78,93,75,89,94
3,Mukesh Nirmal,nirmalmukesh200@gmail.com,Dehradun,72,92,71,96,75
4,rohit,NaN,NaN,87,75,78,90,87
5,Ramakant,ramakantprajapati11@gmail.com,Dehradun,75,84,76,76,96
6,Vinod Kumar Sharma,vinodsharma740860@gmail.com,Kanpur,74,75,94,81,71
7,Gulshan Kumar Ray,raygulshan960@gmail.com,Dehradun,83,73,74,76,94
8,Ashutosh Kumar raj,ashutoshraj822@gmail.com,Patna,89,89,70,97,81
9,Amit kumar,amitpatel8340s@gmail.com,Patna,73,80,71,87,96
10,Astha sachan,asthasachan96@gmail.com,Kanpur,77,77,71,93,72
11,Shail Kumari,shailverma945@gmail.com,Kanpur,80,95,97,92,92
12,Vaishnavi Kesherwani,vaishnavikesherwani786@gmail.com,Allahabad,88,82,90,91,71
13,Rahul Rai,rahul.rai8997@gmail.com,Dehradun,76,75,77,80,78
14,Trapti,traptishakya21@gmail.com,Allahabad,74,91,95,94,98
15,Annapurna Rawat,nainarawat003@gmail.com,Allahabad,79,70,75,96,80

In [11]:
pd.merge(a,b, on ='Name')

,Name,Mail,Location,Maths_x,English,Hindi,Maths_y,Science,Social Science
0,Smriti Ranjan,smritiranjan65@gmail.com,Patna,93,85,83,93,91,94
1,Tannu kumari,tkumari930451@gmail.com,Patna,78,90,75,78,73,75
2,Seema,dksainiaggarwal@gmail.com,Dehradun,78,93,75,78,89,94
3,Mukesh Nirmal,nirmalmukesh200@gmail.com,Dehradun,72,92,71,72,96,75
4,rohit,NaN,NaN,87,75,78,87,90,87
5,Ramakant,ramakantprajapati11@gmail.com,Dehradun,75,84,76,75,76,96
6,Vinod Kumar Sharma,vinodsharma740860@gmail.com,Kanpur,74,75,94,74,81,71
7,Gulshan Kumar Ray,raygulshan960@gmail.com,Dehradun,83,73,74,83,76,94
8,Ashutosh Kumar raj,ashutoshraj822@gmail.com,Patna,89,89,70,89,97,81
9,Amit kumar,amitpatel8340s@gmail.com,Patna,73,80,71,73,87,96
10,Astha sachan,asthasachan96@gmail.com,Kanpur,77,77,71,77,93,72
11,Shail Kumari,shailverma945@gmail.com,Kanpur,80,95,97,80,92,92
12,Vaishnavi Kesherwani,vaishnavikesherwani786@gmail.com,Allahabad,88,82,90,88,91,71
13,Rahul Rai,rahul.rai8997@gmail.com,Dehradun,76,75,77,76,80,78
14,Trapti,traptishakya21@gmail.com,Allahabad,74,91,95,74,94,98
15,Annapurna Rawat,nainarawat003@gmail.com,Allahabad,79,70,75,79,96,80

In [17]:
pd.merge(a,b,on ='Maths')

,Name_x,Mail,Location,Maths,Name_y,English,Hindi,Science,Social Science
0,Smriti Ranjan,smritiranjan65@gmail.com,Patna,93,Smriti Ranjan,85,83,91,94
1,Tannu kumari,tkumari930451@gmail.com,Patna,78,Tannu kumari,90,75,73,75
2,Tannu kumari,tkumari930451@gmail.com,Patna,78,Seema,93,75,89,94
3,Seema,dksainiaggarwal@gmail.com,Dehradun,78,Tannu kumari,90,75,73,75
4,Seema,dksainiaggarwal@gmail.com,Dehradun,78,Seema,93,75,89,94
5,Mukesh Nirmal,nirmalmukesh200@gmail.com,Dehradun,72,Mukesh Nirmal,92,71,96,75
6,rohit,NaN,NaN,87,rohit,75,78,90,87
7,Ramakant,ramakantprajapati11@gmail.com,Dehradun,75,Ramakant,84,76,76,96
8,Vinod Kumar Sharma,vinodsharma740860@gmail.com,Kanpur,74,Vinod Kumar Sharma,75,94,81,71
9,Vinod Kumar Sharma,vinodsharma740860@gmail.com,Kanpur,74,Trapti,91,95,94,98
10,Trapti,traptishakya21@gmail.com,Allahabad,74,Vinod Kumar Sharma,75,94,81,71
11,Trapti,traptishakya21@gmail.com,Allahabad,74,Trapti,91,95,94,98
12,Gulshan Kumar Ray,raygulshan960@gmail.com,Dehradun,83,Gulshan Kumar Ray,73,74,76,94
13,Ashutosh Kumar raj,ashutoshraj822@gmail.com,Patna,89,Ashutosh Kumar raj,89,70,97,81
14,Amit kumar,amitpatel8340s@gmail.com,Patna,73,Amit kumar,80,71,87,96
15,Astha sachan,asthasachan96@gmail.com,Kanpur,77,Astha sachan,77,71,93,72
16,Shail Kumari,shailverma945@gmail.com,Kanpur,80,Shail Kumari,95,97,92,92
17,Vaishnavi Kesherwani,vaishnavikesherwani786@gmail.com,Allahabad,88,Vaishnavi Kesherwani,82,90,91,71
18,Rahul Rai,rahul.rai8997@gmail.com,Dehradun,76,Rahul Rai,75,77,80,78
19,Annapurna Rawat,nainarawat003@gmail.com,Allahabad,79,Annapurna Rawat,70,75,96,80

In [18]:
pd.merge(a,b, how='inner')

,Name,Mail,Location,Maths,English,Hindi,Science,Social Science
0,Smriti Ranjan,smritiranjan65@gmail.com,Patna,93,85,83,91,94
1,Tannu kumari,tkumari930451@gmail.com,Patna,78,90,75,73,75
2,Seema,dksainiaggarwal@gmail.com,Dehradun,78,93,75,89,94
3,Mukesh Nirmal,nirmalmukesh200@gmail.com,Dehradun,72,92,71,96,75
4,rohit,NaN,NaN,87,75,78,90,87
5,Ramakant,ramakantprajapati11@gmail.com,Dehradun,75,84,76,76,96
6,Vinod Kumar Sharma,vinodsharma740860@gmail.com,Kanpur,74,75,94,81,71
7,Gulshan Kumar Ray,raygulshan960@gmail.com,Dehradun,83,73,74,76,94
8,Ashutosh Kumar raj,ashutoshraj822@gmail.com,Patna,89,89,70,97,81
9,Amit kumar,amitpatel8340s@gmail.com,Patna,73,80,71,87,96
10,Astha sachan,asthasachan96@gmail.com,Kanpur,77,77,71,93,72
11,Shail Kumari,shailverma945@gmail.com,Kanpur,80,95,97,92,92
12,Vaishnavi Kesherwani,vaishnavikesherwani786@gmail.com,Allahabad,88,82,90,91,71
13,Rahul Rai,rahul.rai8997@gmail.com,Dehradun,76,75,77,80,78
14,Trapti,traptishakya21@gmail.com,Allahabad,74,91,95,94,98
15,Annapurna Rawat,nainarawat003@gmail.com,Allahabad,79,70,75,96,80

In [19]:
pd.merge(a,b, how='left')

,Name,Mail,Location,Maths,English,Hindi,Science,Social Science
0,Smriti Ranjan,smritiranjan65@gmail.com,Patna,93,85,83,91,94
1,Tannu kumari,tkumari930451@gmail.com,Patna,78,90,75,73,75
2,Seema,dksainiaggarwal@gmail.com,Dehradun,78,93,75,89,94
3,Mukesh Nirmal,nirmalmukesh200@gmail.com,Dehradun,72,92,71,96,75
4,rohit,NaN,NaN,87,75,78,90,87
5,Ramakant,ramakantprajapati11@gmail.com,Dehradun,75,84,76,76,96
6,Vinod Kumar Sharma,vinodsharma740860@gmail.com,Kanpur,74,75,94,81,71
7,Gulshan Kumar Ray,raygulshan960@gmail.com,Dehradun,83,73,74,76,94
8,Ashutosh Kumar raj,ashutoshraj822@gmail.com,Patna,89,89,70,97,81
9,Amit kumar,amitpatel8340s@gmail.com,Patna,73,80,71,87,96
10,Astha sachan,asthasachan96@gmail.com,Kanpur,77,77,71,93,72
11,Shail Kumari,shailverma945@gmail.com,Kanpur,80,95,97,92,92
12,Vaishnavi Kesherwani,vaishnavikesherwani786@gmail.com,Allahabad,88,82,90,91,71
13,Rahul Rai,rahul.rai8997@gmail.com,Dehradun,76,75,77,80,78
14,Trapti,traptishakya21@gmail.com,Allahabad,74,91,95,94,98
15,Annapurna Rawat,nainarawat003@gmail.com,Allahabad,79,70,75,96,80

In [20]:
pd.merge(a,b, how='right')

,Name,Mail,Location,Maths,English,Hindi,Science,Social Science
0,Smriti Ranjan,smritiranjan65@gmail.com,Patna,93,85,83,91,94
1,Tannu kumari,tkumari930451@gmail.com,Patna,78,90,75,73,75
2,Seema,dksainiaggarwal@gmail.com,Dehradun,78,93,75,89,94
3,Mukesh Nirmal,nirmalmukesh200@gmail.com,Dehradun,72,92,71,96,75
4,rohit,NaN,NaN,87,75,78,90,87
5,Ramakant,ramakantprajapati11@gmail.com,Dehradun,75,84,76,76,96
6,Vinod Kumar Sharma,vinodsharma740860@gmail.com,Kanpur,74,75,94,81,71
7,Gulshan Kumar Ray,raygulshan960@gmail.com,Dehradun,83,73,74,76,94
8,Ashutosh Kumar raj,ashutoshraj822@gmail.com,Patna,89,89,70,97,81
9,Amit kumar,amitpatel8340s@gmail.com,Patna,73,80,71,87,96
10,Astha sachan,asthasachan96@gmail.com,Kanpur,77,77,71,93,72
11,Shail Kumari,shailverma945@gmail.com,Kanpur,80,95,97,92,92
12,Vaishnavi Kesherwani,vaishnavikesherwani786@gmail.com,Allahabad,88,82,90,91,71
13,Rahul Rai,rahul.rai8997@gmail.com,Dehradun,76,75,77,80,78
14,Trapti,traptishakya21@gmail.com,Allahabad,74,91,95,94,98
15,Annapurna Rawat,nainarawat003@gmail.com,Allahabad,79,70,75,96,80

In [21]:
pd.merge(a,b, how='outer', indicator= True)

,Name,Mail,Location,Maths,English,Hindi,Science,Social Science,_merge
0,Smriti Ranjan,smritiranjan65@gmail.com,Patna,93,85,83,91,94,both
1,Tannu kumari,tkumari930451@gmail.com,Patna,78,90,75,73,75,both
2,Seema,dksainiaggarwal@gmail.com,Dehradun,78,93,75,89,94,both
3,Mukesh Nirmal,nirmalmukesh200@gmail.com,Dehradun,72,92,71,96,75,both
4,rohit,NaN,NaN,87,75,78,90,87,both
5,Ramakant,ramakantprajapati11@gmail.com,Dehradun,75,84,76,76,96,both
6,Vinod Kumar Sharma,vinodsharma740860@gmail.com,Kanpur,74,75,94,81,71,both
7,Gulshan Kumar Ray,raygulshan960@gmail.com,Dehradun,83,73,74,76,94,both
8,Ashutosh Kumar raj,ashutoshraj822@gmail.com,Patna,89,89,70,97,81,both
9,Amit kumar,amitpatel8340s@gmail.com,Patna,73,80,71,87,96,both
10,Astha sachan,asthasachan96@gmail.com,Kanpur,77,77,71,93,72,both
11,Shail Kumari,shailverma945@gmail.com,Kanpur,80,95,97,92,92,both
12,Vaishnavi Kesherwani,vaishnavikesherwani786@gmail.com,Allahabad,88,82,90,91,71,both
13,Rahul Rai,rahul.rai8997@gmail.com,Dehradun,76,75,77,80,78,both
14,Trapti,traptishakya21@gmail.com,Allahabad,74,91,95,94,98,both
15,Annapurna Rawat,nainarawat003@gmail.com,Allahabad,79,70,75,96,80,both

In [22]:
pd.concat([a,b])

,Name,Mail,Location,Maths,English,Hindi,Science,Social Science
0,Smriti Ranjan,smritiranjan65@gmail.com,Patna,93,NaN,NaN,NaN,NaN
1,Tannu kumari,tkumari930451@gmail.com,Patna,78,NaN,NaN,NaN,NaN
2,Seema,dksainiaggarwal@gmail.com,Dehradun,78,NaN,NaN,NaN,NaN
3,Mukesh Nirmal,nirmalmukesh200@gmail.com,Dehradun,72,NaN,NaN,NaN,NaN
4,rohit,NaN,NaN,87,NaN,NaN,NaN,NaN
5,Ramakant,ramakantprajapati11@gmail.com,Dehradun,75,NaN,NaN,NaN,NaN
6,Vinod Kumar Sharma,vinodsharma740860@gmail.com,Kanpur,74,NaN,NaN,NaN,NaN
7,Gulshan Kumar Ray,raygulshan960@gmail.com,Dehradun,83,NaN,NaN,NaN,NaN
8,Ashutosh Kumar raj,ashutoshraj822@gmail.com,Patna,89,NaN,NaN,NaN,NaN
9,Amit kumar,amitpatel8340s@gmail.com,Patna,73,NaN,NaN,NaN,NaN
10,Astha sachan,asthasachan96@gmail.com,Kanpur,77,NaN,NaN,NaN,NaN
11,Shail Kumari,shailverma945@gmail.com,Kanpur,80,NaN,NaN,NaN,NaN
12,Vaishnavi Kesherwani,vaishnavikesherwani786@gmail.com,Allahabad,88,NaN,NaN,NaN,NaN
13,Rahul Rai,rahul.rai8997@gmail.com,Dehradun,76,NaN,NaN,NaN,NaN
14,Trapti,traptishakya21@gmail.com,Allahabad,74,NaN,NaN,NaN,NaN
15,Annapurna Rawat,nainarawat003@gmail.com,Allahabad,79,NaN,NaN,NaN,NaN
0,Smriti Ranjan,NaN,NaN,93,85.0,83.0,91.0,94.0
1,Tannu kumari,NaN,NaN,78,90.0,75.0,73.0,75.0
2,Seema,NaN,NaN,78,93.0,75.0,89.0,94.0
3,Mukesh Nirmal,NaN,NaN,72,92.0,71.0,96.0,75.0
4,rohit,NaN,NaN,87,75.0,78.0,90.0,87.0
5,Ramakant,NaN,NaN,75,84.0,76.0,76.0,96.0
6,Vinod Kumar Sharma,NaN,NaN,74,75.0,94.0,81.0,71.0
7,Gulshan Kumar Ray,NaN,NaN,83,73.0,74.0,76.0,94.0
8,Ashutosh Kumar raj,NaN,NaN,89,89.0,70.0,97.0,81.0
9,Amit kumar,NaN,NaN,73,80.0,71.0,87.0,96.0
10,Astha sachan,NaN,NaN,77,77.0,71.0,93.0,72.0
11,Shail Kumari,NaN,NaN,80,95.0,97.0,92.0,92.0
12,Vaishnavi Kesherwani,NaN,NaN,88,82.0,90.0,91.0,71.0
13,Rahul Rai,NaN,NaN,76,75.0,77.0,80.0,78.0
14,Trapti,NaN,NaN,74,91.0,95.0,94.0,98.0
15,Annapurna Rawat,NaN,NaN,79,70.0,75.0,96.0,80.0

In [23]:
pd.concat([a,b], axis= 1 ,join ='inner')

,Name,Mail,Location,Maths,Name,English,Hindi,Maths,Science,Social Science
0,Smriti Ranjan,smritiranjan65@gmail.com,Patna,93,Smriti Ranjan,85,83,93,91,94
1,Tannu kumari,tkumari930451@gmail.com,Patna,78,Tannu kumari,90,75,78,73,75
2,Seema,dksainiaggarwal@gmail.com,Dehradun,78,Seema,93,75,78,89,94
3,Mukesh Nirmal,nirmalmukesh200@gmail.com,Dehradun,72,Mukesh Nirmal,92,71,72,96,75
4,rohit,NaN,NaN,87,rohit,75,78,87,90,87
5,Ramakant,ramakantprajapati11@gmail.com,Dehradun,75,Ramakant,84,76,75,76,96
6,Vinod Kumar Sharma,vinodsharma740860@gmail.com,Kanpur,74,Vinod Kumar Sharma,75,94,74,81,71
7,Gulshan Kumar Ray,raygulshan960@gmail.com,Dehradun,83,Gulshan Kumar Ray,73,74,83,76,94
8,Ashutosh Kumar raj,ashutoshraj822@gmail.com,Patna,89,Ashutosh Kumar raj,89,70,89,97,81
9,Amit kumar,amitpatel8340s@gmail.com,Patna,73,Amit kumar,80,71,73,87,96
10,Astha sachan,asthasachan96@gmail.com,Kanpur,77,Astha sachan,77,71,77,93,72
11,Shail Kumari,shailverma945@gmail.com,Kanpur,80,Shail Kumari,95,97,80,92,92
12,Vaishnavi Kesherwani,vaishnavikesherwani786@gmail.com,Allahabad,88,Vaishnavi Kesherwani,82,90,88,91,71
13,Rahul Rai,rahul.rai8997@gmail.com,Dehradun,76,Rahul Rai,75,77,76,80,78
14,Trapti,traptishakya21@gmail.com,Allahabad,74,Trapti,91,95,74,94,98
15,Annapurna Rawat,nainarawat003@gmail.com,Allahabad,79,Annapurna Rawat,70,75,79,96,80

In [25]:
pd.concat([a,b], axis= 1 ,join ='inner', keys=['Details','Marks'])

                 Details                                                     \
                    Name                              Mail   Location Maths
0          Smriti Ranjan          smritiranjan65@gmail.com      Patna    93
1          Tannu kumari            tkumari930451@gmail.com      Patna    78
2                  Seema         dksainiaggarwal@gmail.com   Dehradun    78
3          Mukesh Nirmal         nirmalmukesh200@gmail.com   Dehradun    72
4                  rohit                               NaN        NaN    87
5               Ramakant     ramakantprajapati11@gmail.com   Dehradun    75
6    Vinod Kumar Sharma        vinodsharma740860@gmail.com     Kanpur    74
7     Gulshan Kumar Ray            raygulshan960@gmail.com   Dehradun    83
8    Ashutosh Kumar raj           ashutoshraj822@gmail.com      Patna    89
9             Amit kumar          amitpatel8340s@gmail.com      Patna    73
10          Astha sachan           asthasachan96@gmail.com     Kanpur    77
11          Shail Kumari           shailverma945@gmail.com     Kanpur    80
12  Vaishnavi Kesherwani  vaishnavikesherwani786@gmail.com  Allahabad    88
13             Rahul Rai           rahul.rai8997@gmail.com   Dehradun    76
14                Trapti          traptishakya21@gmail.com  Allahabad    74
15       Annapurna Rawat           nainarawat003@gmail.com  Allahabad    79

                   Marks
                    Name English Hindi Maths Science Social Science
0          Smriti Ranjan      85    83    93      91             94
1          Tannu kumari       90    75    78      73             75
2                  Seema      93    75    78      89             94
3          Mukesh Nirmal      92    71    72      96             75
4                  rohit      75    78    87      90             87
5               Ramakant      84    76    75      76             96
6    Vinod Kumar Sharma       75    94    74      81             71
7     Gulshan Kumar Ray       73    74    83      76             94
8    Ashutosh Kumar raj       89    70    89      97             81
9             Amit kumar      80    71    73      87             96
10          Astha sachan      77    71    77      93             72
11          Shail Kumari      95    97    80      92             92
12  Vaishnavi Kesherwani      82    90    88      91             71
13             Rahul Rai      75    77    76      80             78
14                Trapti      91    95    74      94             98
15       Annapurna Rawat      70    75    79      96             80

In [26]:
pd.concat([a,b], axis= 0 ,join ='inner', keys=['Details','Marks'])

                            Name  Maths
Details 0          Smriti Ranjan     93
        1          Tannu kumari      78
        2                  Seema     78
        3          Mukesh Nirmal     72
        4                  rohit     87
        5               Ramakant     75
        6    Vinod Kumar Sharma      74
        7     Gulshan Kumar Ray      83
        8    Ashutosh Kumar raj      89
        9             Amit kumar     73
        10          Astha sachan     77
        11          Shail Kumari     80
        12  Vaishnavi Kesherwani     88
        13             Rahul Rai     76
        14                Trapti     74
        15       Annapurna Rawat     79
Marks   0          Smriti Ranjan     93
        1          Tannu kumari      78
        2                  Seema     78
        3          Mukesh Nirmal     72
        4                  rohit     87
        5               Ramakant     75
        6    Vinod Kumar Sharma      74
        7     Gulshan Kumar Ray      83
        8    Ashutosh Kumar raj      89
        9             Amit kumar     73
        10          Astha sachan     77
        11          Shail Kumari     80
        12  Vaishnavi Kesherwani     88
        13             Rahul Rai     76
        14                Trapti     74
        15       Annapurna Rawat     79

In [27]:
a1 = a.groupby('Name')
a1

In [37]:
a1.get_group('Trapti')

      Name                      Mail   Location  Maths
14  Trapti  traptishakya21@gmail.com  Allahabad     74

In [40]:
for x , y in a1:
    print(x)
    print(y)

Amit kumar
         Name                      Mail Location  Maths
9  Amit kumar  amitpatel8340s@gmail.com    Patna     73
Annapurna Rawat
               Name                     Mail   Location  Maths
15  Annapurna Rawat  nainarawat003@gmail.com  Allahabad     79
Ashutosh Kumar raj
                  Name                      Mail Location  Maths
8  Ashutosh Kumar raj   ashutoshraj822@gmail.com    Patna     89
Astha sachan
            Name                     Mail Location  Maths
10  Astha sachan  asthasachan96@gmail.com   Kanpur     77
Gulshan Kumar Ray
                 Name                     Mail  Location  Maths
7  Gulshan Kumar Ray   raygulshan960@gmail.com  Dehradun     83
Mukesh Nirmal
            Name                       Mail  Location  Maths
3  Mukesh Nirmal  nirmalmukesh200@gmail.com  Dehradun     72
Rahul Rai
         Name                     Mail  Location  Maths
13  Rahul Rai  rahul.rai8997@gmail.com  Dehradun     76
Ramakant
       Name                           Mail  Location  Maths
5  Ramakant  ramakantprajapati11@gmail.com  Dehradun     75
Seema
    Name                       Mail  Location  Maths
2  Seema  dksainiaggarwal@gmail.com  Dehradun     78
Shail Kumari
            Name                     Mail Location  Maths
11  Shail Kumari  shailverma945@gmail.com   Kanpur     80
Smriti Ranjan
            Name                      Mail Location  Maths
0  Smriti Ranjan  smritiranjan65@gmail.com    Patna     93
Tannu kumari
            Name                     Mail Location  Maths
1  Tannu kumari   tkumari930451@gmail.com    Patna     78
Trapti
      Name                      Mail   Location  Maths
14  Trapti  traptishakya21@gmail.com  Allahabad     74
Vaishnavi Kesherwani
                    Name                              Mail   Location  Maths
12  Vaishnavi Kesherwani  vaishnavikesherwani786@gmail.com  Allahabad     88
Vinod Kumar Sharma
                  Name                         Mail Location  Maths
6  Vinod Kumar Sharma   vinodsharma740860@gmail.com   Kanpur     74
rohit
    Name Mail Location  Maths
4  rohit  NaN      NaN     87

In [41]:
a2 = a.groupby('Maths')
a2

In [43]:
a2.get_group(80)

            Name                     Mail Location  Maths
11  Shail Kumari  shailverma945@gmail.com   Kanpur     80

In [44]:
for x , y in a2:
    print(x)
    print(y)

72
            Name                       Mail  Location  Maths
3  Mukesh Nirmal  nirmalmukesh200@gmail.com  Dehradun     72
73
         Name                      Mail Location  Maths
9  Amit kumar  amitpatel8340s@gmail.com    Patna     73
74
                   Name                         Mail   Location  Maths
6   Vinod Kumar Sharma   vinodsharma740860@gmail.com     Kanpur     74
14               Trapti     traptishakya21@gmail.com  Allahabad     74
75
       Name                           Mail  Location  Maths
5  Ramakant  ramakantprajapati11@gmail.com  Dehradun     75
76
         Name                     Mail  Location  Maths
13  Rahul Rai  rahul.rai8997@gmail.com  Dehradun     76
77
            Name                     Mail Location  Maths
10  Astha sachan  asthasachan96@gmail.com   Kanpur     77
78
            Name                       Mail  Location  Maths
1  Tannu kumari     tkumari930451@gmail.com     Patna     78
2          Seema  dksainiaggarwal@gmail.com  Dehradun     78
79
               Name                     Mail   Location  Maths
15  Annapurna Rawat  nainarawat003@gmail.com  Allahabad     79
80
            Name                     Mail Location  Maths
11  Shail Kumari  shailverma945@gmail.com   Kanpur     80
83
                 Name                     Mail  Location  Maths
7  Gulshan Kumar Ray   raygulshan960@gmail.com  Dehradun     83
87
    Name Mail Location  Maths
4  rohit  NaN      NaN     87
88
                    Name                              Mail   Location  Maths
12  Vaishnavi Kesherwani  vaishnavikesherwani786@gmail.com  Allahabad     88
89
                  Name                      Mail Location  Maths
8  Ashutosh Kumar raj   ashutoshraj822@gmail.com    Patna     89
93
            Name                      Mail Location  Maths
0  Smriti Ranjan  smritiranjan65@gmail.com    Patna     93

In [56]:
a.join(b,rsuffix='_1')

,Name,Mail,Location,Maths,Name_1,English,Hindi,Maths_1,Science,Social Science
0,Smriti Ranjan,smritiranjan65@gmail.com,Patna,93,Smriti Ranjan,85,83,93,91,94
1,Tannu kumari,tkumari930451@gmail.com,Patna,78,Tannu kumari,90,75,78,73,75
2,Seema,dksainiaggarwal@gmail.com,Dehradun,78,Seema,93,75,78,89,94
3,Mukesh Nirmal,nirmalmukesh200@gmail.com,Dehradun,72,Mukesh Nirmal,92,71,72,96,75
4,rohit,NaN,NaN,87,rohit,75,78,87,90,87
5,Ramakant,ramakantprajapati11@gmail.com,Dehradun,75,Ramakant,84,76,75,76,96
6,Vinod Kumar Sharma,vinodsharma740860@gmail.com,Kanpur,74,Vinod Kumar Sharma,75,94,74,81,71
7,Gulshan Kumar Ray,raygulshan960@gmail.com,Dehradun,83,Gulshan Kumar Ray,73,74,83,76,94
8,Ashutosh Kumar raj,ashutoshraj822@gmail.com,Patna,89,Ashutosh Kumar raj,89,70,89,97,81
9,Amit kumar,amitpatel8340s@gmail.com,Patna,73,Amit kumar,80,71,73,87,96
10,Astha sachan,asthasachan96@gmail.com,Kanpur,77,Astha sachan,77,71,77,93,72
11,Shail Kumari,shailverma945@gmail.com,Kanpur,80,Shail Kumari,95,97,80,92,92
12,Vaishnavi Kesherwani,vaishnavikesherwani786@gmail.com,Allahabad,88,Vaishnavi Kesherwani,82,90,88,91,71
13,Rahul Rai,rahul.rai8997@gmail.com,Dehradun,76,Rahul Rai,75,77,76,80,78
14,Trapti,traptishakya21@gmail.com,Allahabad,74,Trapti,91,95,74,94,98
15,Annapurna Rawat,nainarawat003@gmail.com,Allahabad,79,Annapurna Rawat,70,75,79,96,80

In [ ]:
a.join(b,rsuffix='_1')